//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MapEditor.rc
//
#define IDM_MAINMENU                    101
#define IDI_ICON1                       102
#define IDD_TEXTURE_EDITOR              103
#define IDD_MATERIAL_EDITOR             105
#define IDD_MESH_EDITOR                 107
#define IDD_MODEL_EDITOR                111
#define ID_EDITORS_MODELEDITOR          112
#define ID_FILE_SAVEMAPAS               113
#define IDM_MODELEDITOR                 115
#define ID_MOEDIT_FILE_EXIT             116
#define IDD_TUBERS_EDITOR_DIALOG        118
#define IDM_TUBERSEDITOR                119
#define IDD_INSERT_DIALOG               121
#define IDD_SAVE_DIALOG                 122
#define IDD_ACTOR                       125
#define IDD_TUBEDYNAMIC                 126
#define IDD_PATHNODE                    129
#define IDD_CHECKPOINT                  130
#define IDD_EFFECTEDITOR                132
#define IDD_OBJECTALIGN                 133
#define IDD_TUBEADDCHOOSEDIALOG         134
#define IDD_INFO                        135
#define IDD_ACTIOMANAGERDIALOG          136
#define IDD_ABOUT                       137
#define IDD_HELP                        138
#define IDD_POSTPROCESVIEWER            139
#define IDD_PARTICLESYSTEMEDITOR        140
#define IDD_PARTICLESYSTEMPROPERTIES    141
#define IDM_PARTICLEEDITOR              143
#define IDD_SOUNDEDITOR                 144
#define IDD_ACTORTYPEDIALOG             145
#define IDD_INPUTDIALOG                 146
#define IDD_MATERIALPRESETDIALOG        147
#define IDD_LIGHTDIALOG                 149
#define IDD_SKYBOXDIALOG                150
#define IDD_TURNAMENTPROPERTIES         151
#define IDD_TMSETTINGS                  152
#define IDD_MAPDESCRIPTIONDIALOG        153
#define IDD_AIPROFILEDIALOG             154
#define IDD_AIPROFILES                  155
#define IDD_PICKUPLIST                  156
#define IDD_DIALOGPICKUPPROPERTIES      158
#define IDD_TOPENCLOSESTATE             159
#define IDD_TOURNAMENTEDITOR            160
#define IDD_STARTLOACATION              161
#define IDD_OBJECTINSERTDILOG           162
#define IDD_PHYSIC_EDITOR               163
#define IDM_PHYSICEDITOR                164
#define IDD_CLOTHDIALOG                 165
#define IDD_ANIMTEXTUREEDITOR           166
#define IDM_ANIMTEXTUREEDITOR           167
#define IDD_ZONEDIALOG                  168
#define IDD_PORTALDIALOG                169
#define IDD_ANIMATEDMESH                170
#define IDM_ANIMATEDMESHEDITOR          171
#define IDD_BAKINGDIALOG                173
#define IDD_SELECTION                   175
#define IDD_RENDERPHASES                176
#define IDD_PHYSICPROPERTIES            177
#define ID_TE_PREVIEW                   1001
#define ID_MODEDIT_MESHNAME             1011
#define ID_MODEDIT_EDITMESHNAME         1012
#define ID_MODEDIT_QUERYMESHNAME        1013
#define ID_MODEDIT_EDITQUERYMESHNAME    1014
#define ID_MOEDIT_MOREBUTTON            1015
#define ID_MOEDIT_REFRESHBUTTON         1016
#define ID_MOEDIT_MESHPREVIEW           1017
#define ID_MOEDIT_MESHPREVIEWCOMBO      1019
#define IDC_TUBERPREVIEW                1035
#define IDC_TUBERNAME                   1036
#define IDC_MAXSPEED                    1037
#define IDC_PARTMODELNAME               1038
#define IDC_MAXACCELERATION             1039
#define IDC_MANOUVERABILITY             1040
#define IDC_DESCRIPTION                 1041
#define IDC_HP                          1043
#define IDC_PRICE                       1044
#define IDC_WEAPONUPGRADELEVEL          1044
#define IDC_MINEUPGRADELEVEL            1045
#define IDC_TURBOUPGRADELEVEL           1046
#define IDC_PARTQNT                     1048
#define IDC_PARTMODELBROWSE             1059
#define ID_INSERT_TREEVIEW              1069
#define ID_INSERT_INSERTBUTTON          1070
#define ID_INSERT_CANCELBUTTON          1071
#define ID_SAVE_TREEVIEW                1072
#define ID_SAVE_SAVEBUTTON              1078
#define IDC_OK                          1093
#define IDC_POSITIONX                   1094
#define IDC_POSITIONY                   1095
#define IDC_POSITIONZ                   1096
#define IDC_YAW                         1097
#define IDC_PITCH                       1098
#define IDC_ROLL                        1099
#define IDC_MODELNAME                   1100
#define IDC_MODELNAMEBROWSE             1101
#define IDC_LIFETIME                    1102
#define IDC_RENDERABLE                  1103
#define IDC_PHYSICMODELNAMEBROWSE       1103
#define IDC_PMODELNAME                  1107
#define IDC_PMODELNAMEBROWSE            1108
#define IDC_GHOSTOBJECT                 1109
#define IDC_SOUNDBROWSE                 1110
#define IDC_SEQUENCENUMBER              1118
#define IDC_FHDRI                       1119
#define IDC_DIMENSIONX                  1123
#define IDC_DIMENSIONY                  1124
#define IDC_DIMENSIONZ                  1125
#define IDC_INDEX                       1126
#define IDC_LAPCOUNTER                  1127
#define IDC_TE_TYPE                     1132
#define IDC_MATERIALNAME                1133
#define IDC_MAXPARTICLES                1136
#define IDC_ALPHAFROM                   1137
#define IDC_ALPHATO                     1138
#define IDC_GROWFROM                    1139
#define IDC_GROWTO                      1140
#define IDC_GRAVITYX                    1141
#define IDC_GRAVITYY                    1142
#define IDC_GRAVITYZ                    1143
#define IDC_SPREAD                      1144
#define IDC_SPAWNDIRECTIONX             1145
#define IDC_SPAWNDIRECTIONY             1146
#define IDC_SPAWNDIRECTIONZ             1147
#define IDC_SIZERANDOMNESS              1148
#define IDC_TE_WIDTH                    1149
#define IDC_SPINFROM                    1149
#define IDC_TE_HEIGHT                   1150
#define IDC_SPINTO                      1150
#define IDC_TE_DEPTH                    1151
#define IDC_SPINRANDOMNESS              1151
#define IDC_EFFECTNAMEBROWSE            1152
#define IDC_VISIBLESPHERERADIUS         1152
#define IDC_SAVE                        1153
#define IDC_EFFECTNAME                  1155
#define IDC_LOAD                        1156
#define IDC_CLOSE                       1157
#define IDC_TEXTURE1NAME                1159
#define IDC_TEXTURE1SET                 1161
#define IDC_TEXTURE1FIND                1162
#define IDC_TEXTURE2NAME                1163
#define IDC_TEXTURE3NAME                1166
#define IDC_TEXTURE4NAME                1168
#define IDC_TEXTURE5NAME                1170
#define IDC_TEXTURE6NAME                1172
#define IDC_TEXTURE7NAME                1174
#define IDC_TEXTURE8NAME                1176
#define IDC_TEXTURE2SET                 1178
#define IDC_TEXTURE3SET                 1179
#define IDC_TEXTURE4SET                 1180
#define IDC_TEXTURE5SET                 1181
#define IDC_TEXTURE6SET                 1182
#define IDC_TEXTURE7SET                 1183
#define IDC_TEXTURE8SET                 1184
#define IDC_TEXTURE2FIND                1185
#define IDC_TEXTURE3FIND                1186
#define IDC_TEXTURE4FIND                1187
#define IDC_TEXTURE5FIND                1188
#define IDC_TEXTURE6FIND                1189
#define IDC_TEXTURE7FIND                1190
#define IDC_TEXTURE8FIND                1191
#define IDC_ANIMESHED_MATERIALLIST      1193
#define IDC_MESHED_MESHPREVIEW          1194
#define IDC_ALIGNBUTTON                 1195
#define IDC_DELETE                      1195
#define IDC_INFO                        1195
#define IDC_NEWBUTTON                   1195
#define IDC_ADD                         1195
#define IDC_BROWSE                      1195
#define IDC_BROWSEMATERIALBUTTON        1195
#define IDC_DELETESTATEBUTTON           1195
#define IDC_COLORFROMCHOSEB             1195
#define IDC_MATCOLORBUTTON              1195
#define IDC_TOPMATERIALCHOOSE           1195
#define IDC_REMOVEBUTTON                1195
#define IDC_MAPDESCRIPTIONIMAGEBROWSE   1195
#define IDC_ADDAIBUTTON                 1195
#define IDC_INSERT                      1195
#define IDC_BUTTONOK                    1195
#define IDC_ADDTOURNAMENT               1195
#define IDC_MAPDESCRIPTIONBROWSE        1195
#define IDC_ASSIGN_MODELNAME            1195
#define IDC_LOWEMODELBUTTON             1195
#define IDC_RESET                       1195
#define IDC_MESHED_SAVESELECTED         1195
#define IDC_ANIMESHED_CHANGEBUTTON      1195
#define IDC_CANCEL                      1196
#define IDC_COLORTOCHOOSE               1196
#define IDC_LOADMAPIMAGEBROWSE          1196
#define IDC_REMOVEAIBUTTON              1196
#define IDC_EDITTOURNAMENT              1196
#define IDC_LOADINGIMAGEBROWSE          1196
#define IDC_ASSIGN_MODELNAME_ALL        1196
#define IDC_MEDIUMMODELBUTTON           1196
#define IDC_DUPLICATESTATEBUTTON        1196
#define IDC_MESHED_MODELS               1196
#define IDC_XAXISCHECK                  1197
#define IDC_EDITAIBUTTON                1197
#define IDC_REMOVETOURNAMENT            1197
#define IDC_ENDGAMEIMAGEBROWSE          1197
#define IDC_HIGHMODELBUTTON             1197
#define IDC_MOVEUPBUTTON                1197
#define IDC_MESHED_SAVESELECTED_AS      1197
#define IDC_YAXISCHECK                  1198
#define IDC_MOVEDOWNBUTTON              1198
#define IDC_MESHED_MATERIALS            1198
#define IDC_ZAXISCHECK                  1199
#define IDC_MESHED_REMOVESELECTED       1199
#define IDC_YAWCHECK                    1200
#define IDC_MESHED_REFRESHPACKAGE       1200
#define IDC_PITCHCHECK                  1201
#define IDC_MESHED_IMPORTXFILE          1201
#define IDC_ROLLCHECK                   1202
#define IDC_MESHED_MESHES               1202
#define IDC_MESHED_SAVESELECTED_MODEL   1203
#define IDC_MESHED_SAVESELECTED_AS_MODEL 1204
#define IDC_MATERIALTYPE                1205
#define IDC_MESHED_REMOVESELECTED_MODEL 1205
#define IDC_METERIALREFLECTION          1206
#define IDC_GROUPNAME                   1206
#define IDC_PRESETCOMBO                 1206
#define IDC_SPAWNTYPECOMBO              1206
#define IDC_MOVINGTYPE                  1206
#define IDC_TUBERNAMECOMBO              1206
#define IDC_MAPNAMECOMBO                1206
#define IDC_MESHED_COPYATTR             1206
#define IDC_TUNNELCONNECTCOMBO          1207
#define IDC_PACKAGENAME                 1207
#define IDC_ACTIONCOMBO                 1207
#define IDC_RNUM                        1207
#define IDC_ACTORTYPESCOMBO             1207
#define IDC_MATERIALPRESETCOMBO         1207
#define IDC_SPAWINGTYPE                 1207
#define IDC_OBJECT                      1207
#define IDC_TEAMNUMBERCOMBO             1207
#define IDC_MAPTYPE                     1207
#define IDC_TOURNAMENTCOMBO             1207
#define IDC_COMBOTEAMNUM                1207
#define IDC_LIGHTTYPECOMBO              1207
#define IDC_ZONE1NAME                   1207
#define IDC_TE_LOWESTQUALITY            1207
#define IDC_ANIMESHED_MATERIALPRESET    1207
#define IDC_MESHED_PASTEATTR            1207
#define IDC_NAME                        1208
#define IDC_MOVINGTYPECOMBO             1208
#define IDC_RNUM2                       1208
#define IDC_ENDCONDITION                1208
#define IDC_STATECOMBO                  1208
#define IDC_BLENDTYPE                   1208
#define IDC_MESHED_LOAD_MODEL           1208
#define IDC_DESTINATIONNAME             1209
#define IDC_ZONE2NAME                   1209
#define IDC_PARTICLEANGLE               1209
#define IDC_MESHED_COPYALLATTR          1209
#define IDC_DELETEBUTTON                1210
#define IDC_PARTICLEBLENDTYPE           1210
#define IDC_MESHED_PASTEALLATTR         1210
#define IDC_PLAYACTIONBUTTON            1211
#define IDC_STOPREC                     1212
#define IDC_PLAY                        1212
#define IDC_REFRESH                     1212
#define IDC_STEP_UP                     1212
#define IDC_HELPTEXT                    1218
#define IDC_INPUTEDIT                   1218
#define IDC_MATERIALEDIT                1218
#define IDC_TIMEEDIT                    1218
#define IDC_TEXANIMPARAM1               1218
#define IDC_TOPMATERIALEDIT             1218
#define IDC_MAPDESCRIPTION              1218
#define IDC_PROFILENAMEEDIT             1218
#define IDC_RESPAWNTIMEEDIT             1218
#define IDC_PHYSICMODELNAME             1218
#define IDC_LOWMODELEDIT                1218
#define IDC_ANIM_TIME                   1218
#define IDC_SIZEY                       1218
#define IDC_ANIMESHED_ANIMATIONSPEED    1218
#define IDC_EFFECTLIST                  1219
#define IDC_RANGEEDIT                   1219
#define IDC_TEXANIMPARAM2               1219
#define IDC_PROFILECASH                 1219
#define IDC_STATENAME                   1219
#define IDC_MEDIUMMODELEDIT             1219
#define IDC_PREVIEW                     1220
#define IDC_STARTFALLOFFRANGE           1220
#define IDC_TEXANIMPARAM3               1220
#define IDC_LOADINGMUSIC                1220
#define IDC_HIGHMODELEDIT               1220
#define IDC_CLEAR                       1221
#define IDC_TEXANIMPARAM4               1221
#define IDC_LIGTHINTENSITY              1221
#define IDC_REMOVE                      1222
#define IDC_TEXANIMPARAM5               1222
#define IDC_LOADINGIMAGE                1222
#define IDC_SPOTANGLE                   1222
#define IDC_SCREENSCALEX                1223
#define IDC_MATPARAM1                   1223
#define IDC_TIMEFORRACE                 1223
#define IDC_SPECULARINTENSITY           1223
#define IDC_SCREENSCALEY                1224
#define IDC_LOADINGTEXT                 1224
#define IDC_BUMPINTENSITY               1224
#define IDC_ENDGAMETEXT                 1225
#define IDC_ALPHAREF                    1225
#define IDC_MATPARAM2                   1226
#define IDC_MAXTRIALS                   1226
#define IDC_EMITRATE                    1227
#define IDC_MATPARAM3                   1227
#define IDC_LAPCOUNT                    1227
#define IDC_SPOWNVOLUMESIZE             1228
#define IDC_MATPARAM4                   1228
#define IDC_BONUS1ST                    1228
#define IDC_SPOWNPLANEWIDTH             1229
#define IDC_BONUS2ND                    1229
#define IDC_SPECULARPOW                 1229
#define IDC_BONUS3RD                    1230
#define IDC_EMITRATERANDOMNESS          1230
#define IDC_MATERIALALPHA               1230
#define IDC_ENDGAMEIMAGE                1232
#define IDC_ENDGAMEMUSIC                1233
#define IDC_SPOWNPLANEHEIGHT            1238
#define IDC_SPOWNLINEX                  1239
#define IDC_SPOWNLINEY                  1240
#define IDC_SPOWNLINEZ                  1241
#define IDC_STARTVELOCITY               1246
#define IDC_STARTVELOCITYRANDOMNESS     1247
#define IDC_LIFETIMERANDOMNESS          1248
#define IDC_MATERIALBROWSE              1250
#define IDC_SOUNDNAME                   1267
#define IDC_LOADPRESETBUTTON            1268
#define IDC_ADDSTATEBUTTON              1268
#define IDC_PREVIEWAREA                 1268
#define IDC_COLORFROMCHOOSE             1268
#define IDC_ADDOPENLIST                 1268
#define IDC_PLAY_ANIMATION              1268
#define IDC_INPUTSTATIC                 1269
#define IDC_SAVEPRESETBUTTON            1269
#define IDC_REMOVEOPENLIST              1269
#define IDC_REMOVEMAPSTATE              1269
#define IDC_TE_SAVESELECTED             1269
#define IDC_LOCALAXIS                   1270
#define IDC_ADDCLOSELIST                1270
#define IDC_EDITMAPSTATE                1270
#define IDC_TE_REFRESHPACKAGE           1270
#define IDC_PRESETSTATIC                1271
#define IDC_REMOVECLOSELIST             1271
#define IDC_TE_REMOVESELECTED           1271
#define IDC_ADDAI                       1272
#define IDC_TE_SAVESELECTED_AS          1272
#define IDC_TAGEDIT                     1273
#define IDC_REMOVEAI                    1273
#define IDC_TYPECOMBO                   1274
#define IDC_EDITAI                      1274
#define IDC_TE_EXPORTDDS                1274
#define IDC_TELEPORTCHECK               1275
#define IDC_TE_IMPORTTEXTURE            1275
#define IDC_TRIGGERTYPE                 1275
#define IDC_TELEPORTRELATIVE            1276
#define IDC_STATELIST                   1276
#define IDC_ISTRIGGERCHECKBOX           1277
#define IDC_DIFFUSEPICKBUTTON           1277
#define IDC_SPECULARPICKBUTTON          1278
#define IDC_MAXRENDERDISTANCE           1278
#define IDC_SPECULARSTATIC              1279
#define IDC_SOUND                       1279
#define IDC_DIFFUSESTATIC               1280
#define IDC_SOUNDDISTANCE               1280
#define IDC_STATICCHECK                 1282
#define IDC_AFFECTDYNAMICCHECK          1283
#define IDC_YROT                        1283
#define IDC_CHECKSHOULDTERMINATE        1283
#define IDC_MAPREVERSE                  1283
#define IDC_SLEEPONSTART                1283
#define IDC_REALSIZETEXTURE             1283
#define IDC_RECEIVEPROJECTOR            1283
#define IDC_COLORFROMSTATIC             1284
#define IDC_MARKENDOFGAME               1284
#define IDC_COLORTOSTATIC               1285
#define IDC_COLORTOCHOSEB               1285
#define IDC_COLORFROMLABEL              1286
#define IDC_COLORTOLABEL                1287
#define IDC_XROT                        1291
#define IDC_ZROT                        1292
#define IDC_APPLY                       1293
#define IDC_STEP_DOWN                   1294
#define IDC_MATCOLORSTATIC              1295
#define IDC_TEXANIMCOMBO                1296
#define IDC_DESCLIST                    1296
#define IDC_TOURNAMENTTYPE              1296
#define IDC_TEXANIMPARAM1LABEL          1297
#define IDC_TEXANIMPARAM2LABEL          1298
#define IDC_TEXANIMPARAM3LABEL          1299
#define IDC_TEXANIMPARAM4LABEL          1300
#define IDC_TEXANIMPARAM5LABEL          1301
#define IDC_SAVEBUTTON                  1303
#define IDC_WEAPONNAME                  1304
#define IDC_MINENAME                    1305
#define IDC_AILIST                      1305
#define IDC_PICKUPLIST                  1305
#define IDC_OPENLIST                    1305
#define IDC_TOURNAMENTSLIST             1305
#define IDC_ACTORDESC_LIST              1305
#define IDC_PORTALLIST                  1305
#define IDC_TOURNAMENTREQUIRED          1306
#define IDC_CLOSELIST                   1306
#define IDC_MAPSTATESLIST               1306
#define IDC_ANIMESHED_ANIMATIONLIST     1306
#define IDC_AIPROFILES                  1307
#define IDC_PREVBUTTON                  1307
#define IDC_STOP                        1307
#define IDC_BROWSEPROJECTORMATERIAL     1307
#define IDC_MAPDESCRIPTIONIMAGE         1308
#define IDC_GROUPEDIT                   1308
#define IDC_BENDINGSTIFFNESS            1308
#define IDC_FRAMES_PER_SECOND           1308
#define IDC_SIZEX                       1308
#define IDC_PROJECTORMATERIAL           1308
#define IDC_LOADMAPIMAGE                1309
#define IDC_STRETCHINGSTIFFNESS         1309
#define IDC_ALPHA                       1309
#define IDC_SIZEZ                       1309
#define IDC_CORONATEXTURE               1309
#define IDC_DAMPINGCOEF                 1310
#define IDC_REACETIME                   1310
#define IDC_BROWSECORONATEXTURE         1310
#define IDC_FRICTION                    1311
#define IDC_FLARETEXTURE1               1311
#define IDC_TOURNAMENTNAME              1312
#define IDC_PRESSURE                    1312
#define IDC_BROWSEFLARETEXTURE1         1312
#define IDC_ADDRMAPSTATE                1313
#define IDC_TEARFACTOR                  1313
#define IDC_FLARETEXTURE2               1313
#define IDC_BROWSEFLARETEXTURE2         1314
#define IDC_CHECKACTIVE                 1315
#define IDC_ONLYHARDWARE                1315
#define IDC_AUTOATTACH                  1315
#define IDC_IS_LOOP                     1315
#define IDC_TWOWAY                      1315
#define IDC_INTERPOLATESTATES           1315
#define IDC_ANIMATEDMESHES              1315
#define IDC_FOGSTART                    1315
#define IDC_WEAPONSINRACE               1316
#define IDC_THICKNESS                   1316
#define IDC_CASTSHADOWS                 1316
#define IDC_FOGEND                      1316
#define IDC_OPENED                      1317
#define IDC_ATTACHMENTRESPONSECOEF      1317
#define IDC_FLARETEXTURE3               1317
#define IDC_RESPAWNPLAYERS              1318
#define IDC_COLLISIONRESPONSECOEF       1318
#define IDC_BROWSEFLARETEXTURE3         1318
#define IDC_CLOTHGROUP                  1319
#define IDC_FLARETEXTURE4               1319
#define IDC_TEARABLE                    1320
#define IDC_BROWSEFLARETEXTURE4         1320
#define IDC_INSERT_PACKAGETREE          1320
#define IDC_DENSITY                     1321
#define IDC_FLARETEXTURE5               1321
#define IDC_GRAVITY                     1322
#define IDC_BROWSEFLARETEXTURE5         1322
#define IDC_ONLYPPU                     1323
#define IDC_PAUSE                       1324
#define IDC_PICK_COLOR                  1325
#define IDC_COLOR                       1326
#define IDC_ANIMATION_NAME              1327
#define IDC_TEXTUREDIMENSION            1331
#define IDC_FRAMENUM                    1332
#define IDC_TE_TREEVIEW                 1333
#define IDC_MATED_MATERIALLIST          1334
#define IDC_MATED_EFFECTLIST            1335
#define IDC_ANIMESHED_ANIMESHLIST       1335
#define IDC_SPOTANGLEFALLOFF            1336
#define IDC_ANIMESHED_FRAMETREE         1336
#define IDC_PROJECTORCHECK              1337
#define IDC_PROJECTOROMNI               1338
#define IDC_CASTSHADOW                  1338
#define IDC_RECEIVESHADOW               1339
#define IDC_LIGHTSIZEX                  1339
#define IDC_CORONACHECK                 1340
#define IDC_FLARECHECK                  1341
#define IDC_CORONASIZEX                 1342
#define IDC_CORONASIZEY                 1343
#define IDC_FLARESIZEX                  1344
#define IDC_FLARESIZEY                  1345
#define IDC_CORONAALPHA                 1346
#define IDC_FADEINTIME                  1347
#define IDC_FADEOUTTIME                 1348
#define IDC_FLAREALPHA1                 1349
#define IDC_PASSFLARES                  1349
#define IDC_FLAREALPHA2                 1350
#define IDC_MESHED_ATTRIBUTES           1350
#define IDC_LIGHTOCCLUDER               1350
#define IDC_LIGHTSIZEY                  1351
#define IDC_FLAREALPHA3                 1352
#define IDC_MESHED_USENORMALMAP         1352
#define IDC_FLAREALPHA4                 1353
#define IDC_FLAREALPHA5                 1354
#define IDC_MESHED_FINDMATERIAL         1354
#define IDC_MESHED_SETMATERIAL          1355
#define IDC_MATED_TEXTURELIST           1357
#define IDC_ACCEPTLIGHTS                1358
#define IDC_GLOWING                     1359
#define IDC_MESHED_MESHVIEW_WIREFRAME   1360
#define IDC_DOUBLESIDED                 1360
#define IDC_MESHED_MATERIALPRESET       1361
#define IDC_MATED_SAVESELECTED_AS       1362
#define IDC_MATED_SAVESELECTED          1363
#define IDC_SPAWNPARAM1                 1363
#define IDC_MATED_REMOVESELECTED        1364
#define IDC_SPAWNPARAM2                 1364
#define IDC_MATED_NEW                   1365
#define IDC_SPAWNPARAM3                 1365
#define IDC_SPAWNPARAM4                 1366
#define IDC_STATICPARAM1                1367
#define IDC_STATICPARAM2                1368
#define IDC_STATICPARAM3                1369
#define IDC_STATICPARAM4                1370
#define IDC_MESHED_OLD_STYLE            1371
#define IDC_ANIMESHED_PREVIEWAREA       1372
#define IDC_ANIMESHED_TIME              1373
#define IDC_LIGHTED_FIXEDSIZE           1374
#define IDC_MESHED_SHOWONLYSELECTEDMATERIAL 1375
#define IDC_ANITEXED_SAVESELECTED       1376
#define IDC_ANITEXED_SAVESELECTED_AS    1377
#define IDC_SIZEXSTATIC                 1378
#define IDC_SIZEYSTATIC                 1379
#define IDC_PROGRESS                    1381
#define IDC_BAKINGSTATIC                1382
#define IDC_LIGHTMAPSIZE                1383
#define IDC_TEMPBUTTON                  1384
#define IDC_TOTALFRAMES                 1386
#define IDC_RELATIVECHECK               1387
#define ID_MATED_TEXPREVIEW             1388
#define ID_MESHED_TEXPREVIEW            1390
#define IDC_MAP_CLIPDISTANCE            1391
#define IDC_SPINNINGINLIFE              1392
#define IDC_APPLYTOALLOBJECTS           1393
#define IDC_PATHNODE_HEALINGRANGE       1395
#define IDC_PATHNODE_HEALINGSPEED       1396
#define IDC_PATHNODE_FOLLOWTIME         1397
#define IDC_SELECTION_ACTORS            1397
#define IDC_SELECTION_LIGHTS            1398
#define IDC_PATHNODE_HEADLIGHT          1398
#define IDC_SELECTION_PATHNODES         1399
#define IDC_SELECTION_STARTLOCATIONS    1400
#define IDC_FOGCHECK                    1400
#define IDC_SELECTION_PARTICLESYSTEMS   1401
#define IDC_FOGCOLOR                    1401
#define IDC_FOGCOLORBUTTON              1402
#define IDC_SELECTION_ALL               1402
#define IDC_SELECTION_NONE              1404
#define IDC_TEXTURE_NOMIPMAPS           1404
#define IDC_SELECTION_INVERT            1405
#define IDC_SKYCOLOR                    1405
#define IDC_GROUNDCOLOR                 1406
#define IDC_PATHNODE_NODETYPE           1407
#define IDC_INSERT_MULTIMASK            1408
#define IDC_MAP_MUSIC                   1408
#define IDC_MAP_STATMUSIC               1409
#define IDC_RENDERPHASE_ALL             1412
#define IDC_RENDERPHASE_AMBIENT         1413
#define IDC_RENDERPHASE_AMBIENTALPHA    1414
#define IDC_PATHNODE_LEFT               1414
#define IDC_RENDERPHASE_ALPHA           1415
#define IDC_PATHNODE_RIGHT              1415
#define IDC_RENDERPHASE_LIGHTING        1416
#define IDC_PATHNODE_REFRACTION         1416
#define IDC_RENDERPHASE_PROJECTORS      1417
#define IDC_LIGHT_ROTATION              1417
#define IDC_INSERT_MULTI                1417
#define IDC_MATED_TEXPREVIEW            1417
#define IDC_RENDERPHASE_GLOW            1418
#define IDC_MAP_FHDRI0                  1418
#define IDC_RENDERPHASE_REFRACTIONS     1419
#define IDC_MAP_FHDRI1                  1419
#define IDC_LIGHT_ALWAYSSHOWFLARES      1419
#define IDC_RENDERPHASE_FOREGROUND      1420
#define IDC_MAP_FHDRI2                  1420
#define IDC_PATHNODE_SHAKING            1420
#define IDC_RENDERPHASE_FLARES          1421
#define IDC_PHYSICSBUTTON               1421
#define IDC_RENDERPHASE_SKYBOX          1422
#define IDC_BOXDIMENSIONX               1423
#define IDC_BOXDIMENSIONY               1424
#define IDC_BOXDIMENSIONZ               1425
#define IDC_SPHERERADIUS                1426
#define IDC_CAPSULERADIUS               1427
#define IDC_CAPSULEHEIGHT               1428
#define IDC_MASS                        1429
#define IDC_GROUP                       1430
#define IDC_GETFROMOBJECT               1431
#define IDC_EFFECTS_REFRESH             1431
#define IDC_TELEPORTRADIUS              1432
#define IDM_FILE_EXIT                   40001
#define ID_EDITORS_TEXTUREEDITOR        40002
#define ID_EDITORS_MATERIALEDITOR       40003
#define ID_MOEDIT_FILE_SAVE             40008
#define ID_MOEDIT_FILE_OPEN             40009
#define ID_MOEDIT_MESHVIEW_WIREFRAME    40010
#define ID_TUBERSEDITOR_FILE_NEW        40015
#define ID_TUBERSEDITOR_FILE_SAVE       40017
#define ID_TUBERSEDITOR_FILE_EXIT       40018
#define ID_EDITORS_TUBERSEDITOR         40020
#define ID_TUBERSEDITOR_MODEL_REFRESHPREVIEW 40021
#define ID_MAPEDIT_FILE_NEW             40022
#define ID_CAMERA_TOPVIEW               40038
#define ID_CAMERA_FRONTVIEW             40039
#define ID_CAMERA_CAMERALOOK            40040
#define ID_CAMERA_LEFT                  40041
#define ID_EDITORS_EFFECTEDITOR         40045
#define ID_OPTIONS_ALIGN                40052
#define ID_EDIT_UNDO2                   40054
#define ID_VIEW_GRID                    40057
#define ID_FILE_LOADMAP                 40058
#define ID_TUBERSEDITOR_FILE_LOAD       40059
#define ID_HELP_HELP                    40060
#define ID_HELP_ABOUT                   40061
#define ID_VIEW_POSTPROCESES            40062
#define ID_EDITORS_PARTICLESYSTEMEDITOR 40064
#define IDM_PARTICLEEDITOR_NEW          40069
#define IDM_PARTICLEEDITOR_LOAD         40070
#define IDM_PARTICLEEDITOR_SAVE         40071
#define IDM_PARTICLEEDITOR_EXIT         40072
#define ID_EDITORS_SOUNDEDITOR          40073
#define ID_EDIT_COPY40074               40074
#define ID_INSERTMENU_OBJECT            40076
#define ID_EDIT_RADIALARRAY             40078
#define ID_EDIT_ARRAY                   40079
#define ID_EDIT_FLIP                    40080
#define ID_OPTIONS_MATERIALPRESETDEFAULT 40081
#define ID_OPTIONS_CALCULATESTATICLIGHTS 40082
#define ID_VIEW_SHOW                    40083
#define ID_VIEW_ACTIONMANAGMENT         40084
#define ID_INSERT_SETSKYBOX             40085
#define ID_OPTIONS_MAPDESCRIPTION       40086
#define ID_OPTIONS_AILIST               40088
#define ID_OPTIONS_TOURNAMENTEDITOR     40089
#define ID_FILE_OPENFROMSSB             40090
#define ID_FILE_OPENFROMPACKAGE         40091
#define ID_FILE_EXIT                    40092
#define ID_EDITORS_PHYSICMODELEDITOR    40094
#define ID_SAVE_TO_PACKAGE              40095
#define ID_FILE_MAKETRIANGLEMESHFROMMODEL 40096
#define ID_EDIT_HIDEOBJECT              40097
#define ID_EDIT_SHOWALLHIDDEN           40098
#define ID_OPTIONS_CALCULATESELECTEDSTATIC 40101
#define ID_EDITORS_ANIMTEXTUREEDITOR    40102
#define ID_FILE_OPENFROMPACKAGE40104    40104
#define ID_FILE_SAVETOPACKAGE           40105
#define ID_FILE_EXIT40106               40106
#define ID_INSERT_INSERTFRAMEATSTART    40107
#define ID_INSERT_INSERTFRAMEONEND      40108
#define ID_INSERT_INSERTALLFRAMES       40109
#define ID_FILENEW                      40110
#define ID_DISPLAYQUALITY_LOW           40112
#define ID_DISPLAYQUALITY_MIDIUM        40113
#define ID_DISPLAYQUALITY_HIGH          40114
#define ID_VIEW_ZONESANDPORTALS         40116
#define ID_FILE_LOADANIMMESHFROMXFILE   40117
#define ID_ANIMATION_PLAY               40121
#define ID_ANIMATION_STOP               40122
#define ID_ANIMATION_PAUSE              40123
#define ID_ANIMATION_SPEEDUP            40124
#define ID_ANIMATION_SPEEDDOWN          40125
#define ID_ANIMATION_NEXTANIMATION      40126
#define ID_ANIMATION_PREVANIMATION      40127
#define ID_EDITORS_ANIMMESHEDITOR       40128
#define ID_FILE_EXPORTTOOBJ             40129
#define ID_EDIT_FIXSTARTLOCATIONS       40135
#define ID_VIEW_SHADOWS                 40136
#define ID_VIEW_SPECULAR                40137
#define ID_VIEW_BUMPING                 40138
#define ID_ANISOTROPIC_2X               40141
#define ID_ANISOTROPIC_4X               40142
#define ID_ANISOTROPIC_8                40143
#define ID_ANISOTROPIC_16X              40144
#define ID_ANISOTROPIC_OFF              40145
#define ID_ANTIALIASING_OFF             40147
#define ID_ANTIALIASING_2X              40148
#define ID_ANTIALIASING_4X              40149
#define ID_ANTIALIASING_6X              40150
#define ID_ANTIALIASING_8X              40151
#define ID_ANTIALIASING_16X             40152
#define ID_EDITORS_MESHEDITOR           40154
#define ID_OPTIONS_COMPACTPACKAGE       40156
#define ID_OPTIONS_CLEARALLLIGHTSONMAP  40159
#define ID_OPTIONS_CALCULATESIMPLELIGHTS 40160
#define ID_OPTIONS_CALCULATESIMPLESELECTEDLIGHT 40161
#define ID_VIEW_SHOWHIDE                40163
#define ID_VIEW_GLOW                    40166
#define ID_VIEW_REFRACTION              40168
#define ID_VIEW_MOTIONBLUR              40169
#define ID_VIEW_ADDEDPOSTPROCESSES      40170
#define ID_VIEW_PIXELMOTIONBLUR         40171
#define ID_RENDERPHASES                 40173
#define ID_EDIT_FIXPATHNODES            40175
#define ID_VIEW_SHOWHIDEPATHNODES       40178
#define ID_EDIT_FIXMODELS               40179

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        178
#define _APS_NEXT_COMMAND_VALUE         40180
#define _APS_NEXT_CONTROL_VALUE         1433
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
