#ifndef _ACTORTAGS_H
#define _ACTORTAGS_H


#include <WeActor.h>


#define ACTORTYPE_ACTOR				WETYPE_ACTOR

#define ACTORTYPE_TUBEPART			1
#define ACTORTYPE_DYNAMICTUBEPART	2
#define ACTORTYPE_SMOKE				3
#define ACTORTYPE_EXPLOSION			4
#define ACTORTYPE_CHECKPOINT		5
#define ACTORTYPE_STARTINGLOCATION	6
#define ACTORTYPE_PATHNODE			7
#define ACTORTYPE_TUBER				8
#define ACTORTYPE_WEAPON			9
#define ACTORTYPE_PHYSICMODEL		10
#define ACTORTYPE_MINE				11
#define ACTORTYPE_TRIGGER			12
#define ACTORTYPE_FRAGMENT			13


#endif