/*
       File: CPickUpFactory.h
	   Author: Tomislav Kukic
	   Date: 23.06.2006
	   Version: 1.0
*/



#ifndef _CPickUpFactory_h_
#define _CPickUpFactory_h_

class CPickUp;


#define PICKUPTYPE_HEALTH				10001
#define PICKUPTYPE_RANDOMWEAPON			10002
#define	PICKUPTYPE_NUKEROCKET			10003
#define PICKUPTYPE_QUANTUMLASER			10004
#define PICKUPTYPE_MINIROCKETS			10005
#define PICKUPTYPE_FRONTFIELDGENERATOR	10006
#define PICKUPTYPE_SLOWINGROCKET		10007
#define PICKUPTYPE_TRANSLOCATOR			10008
#define PICKUPTYPE_MINIGUN				10009
#define PICKUPTYPE_SUPERNUKEMINE		10010
#define PICKUPTYPE_BLURMINE				10011
#define PICKUPTYPE_MOVINGMINE			10012
#define PICKUPTYPE_INVISIBLEMINE		10013
#define PICKUPTYPE_FORCEFIELDMINE		10014
#define PICKUPTYPE_ELECTRICMINE			10015
#define PICKUPTYPE_GRAVITYMINE			10016
#define PICKUPTYPE_HOMINGMINE			10017
#define PICKUPTYPE_PROXIMITYMINE		10018
#define PICKUPTYPE_SLOWINGMINE			10019
#define PICKUPTYPE_SMOKEMINE			10020
#define PICKUPTYPE_STANDARDMINE			10021
#define PICKUPTYPE_STANDARDROCKET		10022
#define PICKUPTYPE_STANDARDLASER		10023
#define PICKUPTYPE_DOUBLELASER			10024
#define PICKUPTYPE_QUADLASER			10025
#define PICKUPTYPE_COINSMALL			10026
#define PICKUPTYPE_COINMEDIUM			10027
#define PICKUPTYPE_COINLARGE			10028
#define PICKUPTYPE_INVISIBILITY			10029
#define PICKUPTYPE_INVULNERABILITY		10030
#define PICKUPTYPE_DOUBLEDAMAGE			10031
#define PICKUPTYPE_QUADDAMAGE			10032


typedef int PICKUPTYPE;



class CPickUpFactory
{
protected:
	bool			WeaponPickupsActive;

public:
	CPickUpFactory();
	~CPickUpFactory();

	static CPickUpFactory* Instance;

	CPickUp* MakePickUp(PICKUPTYPE ID);

	void			SetWeaponPickupsActive(bool BooleanVariableThatActivatesWeaponPickups);
	bool			AreWeaponPickupsActive();
};



#endif
